# Generated by Django 5.1.1 on 2024-09-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesitem',
            name='cost',
            field=models.PositiveIntegerField(default=None, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
