# Generated by Django 5.1.1 on 2024-09-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_clothesitem_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesitem',
            name='cost',
            field=models.PositiveIntegerField(default=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='publication_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата и время публикации'),
        ),
    ]
